import type { Sql } from 'postgres';

import type { MigrationDefinition } from './types';

const upStatements = [
  `CREATE TABLE IF NOT EXISTS "AgentProfiles" (
    "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "UserId" uuid NOT NULL,
    "AgentCode" varchar(50) NOT NULL,
    "DisplayName" varchar(200) NOT NULL,
    "CreatedAtUtc" timestamptz DEFAULT NOW() NOT NULL,
    "UpdatedAtUtc" timestamptz DEFAULT NOW() NOT NULL,
    "DeletedAtUtc" timestamptz,
    CONSTRAINT "ux_agentprofiles_userid" UNIQUE ("UserId"),
    CONSTRAINT "ux_agentprofiles_agentcode" UNIQUE ("AgentCode"),
    CONSTRAINT "fk_agentprofiles_userid" FOREIGN KEY ("UserId") REFERENCES "UserAccounts"("Id") ON DELETE RESTRICT
  )`,
  // NOTE: Not using CONCURRENTLY here — this is a bootstrap migration that runs before
  // the app serves traffic, so a plain index build (which holds a brief lock) is acceptable
  // and avoids the transaction-boundary limitations that can cause Supabase statement timeouts.
  'CREATE INDEX IF NOT EXISTS idx_agentprofiles_userid ON "AgentProfiles"("UserId")',
];

const downStatements = [
  'DROP INDEX IF EXISTS idx_agentprofiles_userid',
  'ALTER TABLE IF EXISTS "AgentProfiles" DROP CONSTRAINT IF EXISTS "fk_agentprofiles_userid"',
  'DROP TABLE IF EXISTS "AgentProfiles"',
];

export const agentProfilesMigration: MigrationDefinition = {
  id: '002_AgentProfiles',
  async up(sql: Sql) {
    // Raw SQL is required because CONCURRENTLY indexes and explicit rollback steps are not generated by Drizzle ORM.
    for (const statement of upStatements) {
      await sql.unsafe(statement);
    }
  },
  async down(sql: Sql) {
    // Raw SQL is required to remove the FK and index explicitly before table teardown.
    for (const statement of downStatements) {
      await sql.unsafe(statement);
    }
  },
};
